// DivisionX Card — Design Tokens (Dark Navy + Neon Cyan)
// Generated by Claude Design, adapted for Next.js project
//
// ใช้ได้ 2 ทาง:
// 1. import ใน React:  import { tokens, dxColors } from "../shared/design-tokens"
// 2. require ใน Tailwind config (CommonJS): const { dxColors } = require("./components/shared/design-tokens")

// ─────────────────────────────────────────────
// Raw tokens (structured) — ใช้ใน runtime React
// ─────────────────────────────────────────────
const tokens = {
  bg: {
    page:     "#0A1628",
    surface:  "#132947",
    card:     "#1A2F52",
    elevated: "#1E3A5F",
    input:    "#0F1F3D",
    sidebar:  "#0D1E38",
  },
  accent: {
    cyan:       "#00D4FF",
    cyanBright: "#00E5FF",
    cyanSoft:   "#4FC3F7",
    cyanDim:    "#007EA7",
    glow:       "rgba(0,212,255,0.35)",
    glowSoft:   "rgba(0,212,255,0.15)",
  },
  text: {
    primary:   "#FFFFFF",
    secondary: "#B8C5E0",
    muted:     "#7A8BA8",
    disabled:  "#4A5A7A",
    onAccent:  "#0A1628",
  },
  semantic: {
    success: "#00FF88",
    warning: "#FFC857",
    danger:  "#FF4466",
    info:    "#00D4FF",
  },
  border: {
    subtle: "#1E3A5F",
    strong: "#2A4472",
    glow:   "rgba(0,212,255,0.4)",
  },
  series: {
    OP:  { main: "#4FC3F7", bg: "rgba(79,195,247,0.12)" },
    PRB: { main: "#B794F6", bg: "rgba(183,148,246,0.12)" },
    EB:  { main: "#68D391", bg: "rgba(104,211,145,0.12)" },
  },
  chart: ["#00D4FF", "#B794F6", "#68D391", "#FFC857", "#FF4466", "#4FC3F7"],
}

// ─────────────────────────────────────────────
// Flat palette — สำหรับ Tailwind config (ใช้เป็น classes เช่น bg-dx-card)
// ─────────────────────────────────────────────
const dxColors = {
  // Backgrounds
  bg:       tokens.bg.page,      // bg-dx-bg
  surface:  tokens.bg.surface,   // bg-dx-surface
  card:     tokens.bg.card,      // bg-dx-card
  elevated: tokens.bg.elevated,  // bg-dx-elevated
  input:    tokens.bg.input,     // bg-dx-input
  sidebar:  tokens.bg.sidebar,   // bg-dx-sidebar

  // Accent (cyan)
  accent:        tokens.accent.cyan,        // bg-dx-accent / text-dx-accent
  "accent-hi":   tokens.accent.cyanBright,  // bright hover
  "accent-soft": tokens.accent.cyanSoft,    // soft hover
  "accent-dim":  tokens.accent.cyanDim,     // dim / disabled

  // Text
  text:              tokens.text.primary,     // text-dx-text
  "text-secondary":  tokens.text.secondary,   // text-dx-text-secondary
  "text-muted":      tokens.text.muted,       // text-dx-text-muted
  "text-disabled":   tokens.text.disabled,
  "text-on-accent":  tokens.text.onAccent,    // text on cyan button

  // Border
  "border-subtle": tokens.border.subtle,  // border-dx-border-subtle
  "border-strong": tokens.border.strong,

  // Semantic
  success: tokens.semantic.success,
  warning: tokens.semantic.warning,
  danger:  tokens.semantic.danger,
  info:    tokens.semantic.info,

  // SKU series
  "series-op":  tokens.series.OP.main,
  "series-prb": tokens.series.PRB.main,
  "series-eb":  tokens.series.EB.main,
}

// ─────────────────────────────────────────────
// Exports (CommonJS for Tailwind config + ESM interop for React)
// ─────────────────────────────────────────────
module.exports = { tokens, dxColors }
